module.exports = {
 "users": {
  "근접 공격 결정타": "rank_melee_lastshot",
  "단독 처치": "rank_solo_kill",
  "임무 기여 처치": "rank_mission_kill",
  "결정타": "rank_lastshot",
  "준 피해": "rank_deal",
  "처치": "rank_kill",
  "환경 요소로 처치": "rank_environment_kill",
  "동시 처치": "rank_onecombo",
  "치유": "rank_heal",
  "처치 시야 지원": "rank_view_support",
  "순간이동기 파괴": "rank_destroy_teleport",
  "처치 - 한 게임 최고기록": "rank_most_kill",
  "결정타 - 한 게임 최고기록": "rank_most_lastshot",
  "준 피해 - 한 게임 최고기록": "rank_most_deal",
  "치유 - 한 게임 최고기록": "rank_most_heal",
  "방어형 도움 - 한 게임 최고기록": "rank_best_defence_support",
  "공격형 도움 - 한 게임 최고기록": "rank_best_attack_support",
  "임무 기여 처치 - 한 게임 최고기록": "rank_most_mission_kill",
  "임무 기여 시간 - 한 게임 최고기록": "rank_most_mission_time",
  "동시 처치 - 최고기록": "rank_most_onecombo",
  "단독 처치 - 한 게임 최고기록": "rank_most_solo_kill",
  "폭주 시간 - 한 게임 최고기록": "rank_most_flood_time",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "칭찬 카드": "rank_card",
  "메달 - 금": "rank_gold_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 동": "rank_bronze_medal",
  "승리한 게임": "rank_win",
  "치른 게임": "rank_game_count",
  "폭주 시간": "rank_flood_time",
  "임무 기여 시간": "rank_mission_time",
  "플레이 시간": "rank_playtime",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_most_melee_lastshot",
  "방어형 도움": "rank_defence_support",
  "공격형 도움": "rank_attack_support"
 },
 "reaper": {
  "거둔 영혼": "rank_soul_consumed",
  "죽음의 꽃으로 처치": "rank_death_blossom_kill",
  "거둔 영혼 - 한 게임 최고기록": "rank_most_soul_consumed",
  "죽음의 꽃으로 처치 - 한 게임 최고기록": "rank_most_death_blossom_kill",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_most_melee_lastshot",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "tracer": {
  "펄스 폭탄으로 처치": "rank_pulse_bomb_kill",
  "펄스 폭탄으로 처치 - 한 게임 최고기록": "rank_best_pulse_bomb_kill_in_game",
  "펄스 폭탄 부착 - 한 게임 최고기록": "rank_best_puls_bomb_attached_in_game",
  "펄스 폭탄 부착": "rank_pulse_bomb_attached",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "mercy": {
  "부활한 플레이어": "rank_resurrected",
  "부활한 플레이어 - 한 게임 최고기록": "rank_best_resurrected_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "블라스터로 처치": "rank_blaster_kill",
  "블라스터로 처치 - 한 게임 최고기록": "rank_best_blaster_kill_in_game",
  "공격형 도움": "rank_attack_support",
  "공격형 도움 - 한 게임 최고기록": "rank_best_attack_support_in_game",
  "방어형 도움": "rank_defence_support",
  "방어형 도움 - 한 게임 최고기록": "rank_best_defence_support_in_game"
 },
 "hanzo": {
  "용의 일격으로 처치": "rank_dragonstrike_kill",
  "용의 일격으로 처치 - 한 게임 최고기록": "rank_best_dragonstrike_kill_in_game",
  "갈래 화살로 처치": "rank_scatter_arrow_kill",
  "갈래 화살로 처치 - 한 게임 최고기록": "rank_best_scatter_arrow_kill_in_game",
  "처치 시야 지원 - 한 게임 최고기록": "rank_best_view_support_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "torbjon": {
  "생성한 방어구 팩": "rank_armor_pack_created",
  "토르비욘이 직접 처치": "rank_torbjon_kill",
  "포탑으로 처치": "rank_turret_kill",
  "토르비욘이 직접 처치 - 한 게임 최고기록": "rank_best_torbjon_kill_in_game",
  "초고열 용광로로 처치": "rank_molten_core_kill",
  "초고열 용광로로 처치 - 한 게임 최고기록": "rank_best_molten_core_kill_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "reinhardt": {
  "막은 피해": "rank_damage_blocked",
  "막은 피해 - 한 게임 최고기록": "rank_best_damage_blocked_in_game",
  "돌진으로 처치": "rank_charge_kill",
  "돌진으로 처치 - 한 게임 최고기록": "rank_best_charge_kill_in_game",
  "화염 강타로 처치": "rank_fire_strike_kill",
  "화염 강타로 처치 - 한 게임 최고기록": "rank_best_fire_strike_kill_in_game",
  "대지분쇄로 처치": "rank_earthshatter_kill",
  "대지분쇄로 처치 - 한 게임 최고기록": "rank_best_earthshatter_kill_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "pharah": {
  "로켓 명중": "rank_rocket_hit",
  "포화로 처치": "rank_barrage_kill",
  "로켓 명중 - 한 게임 최고기록": "rank_best_rocket_hit_in_game",
  "포화로 처치 - 한 게임 최고기록": "rank_best_barrage_kill_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate"
 },
 "winston": {
  "밀쳐낸 플레이어": "rank_knocked_back",
  "막은 피해": "rank_damage_blocked",
  "막은 피해 - 한 게임 최고기록": "rank_best_damage_blocked_in_game",
  "밀쳐낸 플레이어 - 한 게임 최고기록": "rank_best_knocked_back_in_game",
  "근접 공격으로 처치": "rank_melee_kill",
  "근접 공격으로 처치 - 한 게임 최고기록": "rank_best_melee_kill_in_game",
  "점프 팩으로 처치": "rank_jump_pack_kill",
  "점프 팩으로 처치 - 한 게임 최고기록": "rank_best_jump_pack_kill_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "원시의 분노로 처치": "rank_primal_rage_kill",
  "원시의 분노로 처치 - 한 게임 최고기록": "rank_best_primal_rage_kill_in_game"
 },
 "widowmaker": {
  "맹독 지뢰로 처치": "rank_venom_mine_kill",
  "저격 치명타": "rank_scoped_critical",
  "저격 치명타 - 한 게임 최고기록": "rank_best_scoped_critical_in_game",
  "맹독 지뢰로 처치 - 한 게임 최고기록": "rank_best_venom_mine_kill_in_game",
  "처치 시야 지원 - 한 게임 최고기록": "rank_best_view_support_in_game",
  "저격 명중률 - 한 게임 최고기록": "rank_best_scoped_accuracy_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "저격 명중률": "rank_scoped_accuracy",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "bastion": {
  "수색 모드로 처치": "rank_recon_kill",
  "경계 모드로 처치": "rank_sentry_kill",
  "전차 모드로 처치": "rank_tank_kill",
  "경계 모드로 처치 - 한 게임 최고기록": "rank_best_sentry_kill_in_game",
  "전차 모드로 처치 - 한 게임 최고기록": "rank_best_tank_kill_in_game",
  "수색 모드로 처치 - 한 게임 최고기록": "rank_best_recon_kill_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "symmetra": {
  "감시 포탑으로 처치": "rank_turret_kill",
  "감시 포탑으로 처치 - 한 게임 최고기록": "rank_best_turret_kill_in_game",
  "순간이동한 플레이어": "rank_player_teleported",
  "순간이동한 플레이어 - 한 게임 최고기록": "rank_best_player_teleported_in_game",
  "보호막 제공": "rank_shield_provided",
  "보호막 제공 - 한 게임 최고기록": "rank_best_shield_provided_in_game",
  "순간이동기 가동 시간": "rank_teleport_uptime",
  "순간이동기 가동 시간 - 한 게임 최고 기록": "rank_best_teleport_uptime_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "zenyatta": {
  "초월로 치유 - 최고기록": "rank_best_transcendence_heal",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "초월로 치유": "rank_transcendence_heal",
  "공격형 도움": "rank_attack_support",
  "공격형 도움 - 한 게임 최고기록": "rank_best_attack_support_in_game",
  "방어형 도움": "rank_defence_support",
  "방어형 도움 - 한 게임 최고기록": "rank_best_defence_support_in_game",
 },
 "genji": {
  "용검으로 처치": "rank_dragonblade_kill",
  "용검으로 처치 - 한 게임 최고기록": "rank_best_dragonblade_kill_in_game",
  "튕겨낸 피해": "rank_damage_reflected",
  "튕겨낸 피해 - 한 게임 최고기록": "rank_best_damage_reflected_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "roadhog": {
  "갈고리로 끌어오기 - 한 게임 최고기록": "rank_best_hook_in_game",
  "갈고리로 끌어오기": "rank_hook",
  "갈고리 시도": "rank_hook_attempted",
  "돼재앙으로 처치 - 한 게임 최고기록": "rank_best_wholehog_kill_in_game",
  "돼재앙으로 처치": "rank_wholehog_kill",
  "갈고리 명중률 - 한 게임 최고기록": "rank_best_hook_accuracy_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "갈고리 명중률": "rank_hook_accuracy",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "mccree": {
  "황야의 무법자로 처치": "rank_deadeye_kill",
  "황야의 무법자로 처치 - 한 게임 최고기록": "rank_best_deadeye_kill_in_game",
  "피스키퍼 난사로 처치": "rank_fan_the_hammer_kill",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "피스키퍼 난사로 처치 - 한 게임 최고기록": "rank_best_fan_the_hammer_kill_in_game"
 },
 "junkrat": {
  "덫에 걸린 적 - 한 게임 최고기록": "rank_best_trapped_enemy_in_game",
  "덫에 걸린 적": "rank_trapped_enemy",
  "죽이는 타이어로 처치 - 한 게임 최고기록": "rank_best_riptire_kill_in_game",
  "죽이는 타이어로 처치": "rank_riptire_kill",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "분당 덫에 걸린 적": "rank_trapped_enemy_per_minute",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "zarya": {
  "막은 피해": "rank_damage_blocked",
  "막은 피해 - 한 게임 최고기록": "rank_best_damage_blocked_in_game",
  "중력탄으로 처치 누적기록": "rank_graviton_surge_kill",
  "중력탄으로 처치 - 한 게임 최고기록": "rank_best_graviton_kill_in_game",
  "고에너지로 처치 - 한 게임 최고기록": "rank_best_high_energy_kill_in_game",
  "고에너지로 처치": "rank_high_energy_kill",
  "방벽 씌우기": "rank_barrier",
  "평균 에너지 - 한 게임 최고기록": "rank_best_average_energy_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "방벽 씌우기 - 한 게임 최고기록": "rank_best_barrier_in_game"
 },
 "soldier": {
  "나선 로켓으로 처치 - 한 게임 최고기록": "rank_best_helix_rocket_kill_in_game",
  "나선 로켓으로 처치": "rank_helix_rocket_kill",
  "전술 조준경으로 처치": "rank_tactical_visor_kill",
  "전술 조준경으로 처치 - 한 게임 최고기록": "rank_best_tactical_visor_kill_in_game",
  "생체장 생성": "rank_biotic_field_deployed",
  "생체장으로 치유": "rank_biotic_field_heal",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo"
 },
 "lucio": {
  "소리 방벽 제공": "rank_sound_barrier",
  "소리 방벽 제공 - 한 게임 최고기록": "rank_best_sound_barrier_in_game",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "공격형 도움": "rank_attack_support",
  "공격형 도움 - 한 게임 최고기록": "rank_best_attack_support_in_game",
  "방어형 도움": "rank_defence_support",
  "방어형 도움 - 한 게임 최고기록": "rank_best_defence_support_in_game"
 },
 "dva": {
  "호출한 로봇": "rank_mech_called",
  "호출한 로봇 - 한 게임 최고기록": "rank_best_mech_called_in_game",
  "막은 피해 - 한 게임 최고기록": "rank_best_damage_blocked_in_game",
  "막은 피해": "rank_damage_blocked",
  "파괴된 로봇": "rank_mech_destroyed",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "자폭으로 처치": "rank_self_destruct_kill",
  "자폭으로 처치 - 한 게임 최고기록": "rank_best_self_destruct_kill"
 },
 "mei": {
  "얼린 적": "rank_enemy_frozen",
  "얼린 적 - 한 게임 최고기록": "rank_best_enemy_frozen_in_game",
  "눈보라로 처치 - 한 게임 최고기록": "rank_best_blizzard_kill_in_game",
  "눈보라로 처치": "rank_blizzard_kill",
  "막은 피해 - 한 게임 최고기록": "rank_best_damage_blocked_in_game",
  "막은 피해": "rank_damage_blocked",
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "처치 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo" 
 },
 "ana": {
  "근접 공격 결정타 - 한 게임 최고기록": "rank_best_melee_lastshot_in_game",
  "나노 강화제 주입": "rank_nano_boosts_applied",
  "나노 강화제 도움": "rank_nano_boosts_support",
  "나노 강화제 도움 - 한 게임 최고기록": "rank_best_nano_boosts_support_in_game",
  "소총 명중률": "rank_unscoped_accuracy",
  "저격 명중률": "rank_scoped_accuracy",
  "처치": "rank_kill",
  "결정타": "rank_lastshot",
  "단독 처치": "rank_solo_kill",
  "준 피해": "rank_deal",
  "임무 기여 처치": "rank_mission_kill",
  "동시 처치": "rank_onecombo",
  "근접 공격 결정타": "rank_melee_lastshot",
  "치명타": "rank_critical",
  "치명타 명중률": "rank_critical_accuracy",
  "목숨당 처치": "rank_kda",
  "명중률": "rank_accuracy",
  "치유": "rank_heal",
  "순간이동기 파괴": "rank_destroy_teleport",
  "자가 치유": "rank_self_heal",
  "공격형 도움": "rank_attack_support",
  "처치 - 한 목숨 최고기록": "rank_best_kill_in_life",
  "준 피해 - 한 목숨 최고기록": "rank_best_deal_in_life",
  "치유 - 한 목숨 최고기록": "rank_best_heal_in_life",
  "준 피해 - 한 게임 최고기록": "rank_best_deal_in_game",
  "치유 - 한 게임 최고기록": "rank_best_heal_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_kill_in_game",
  "결정타 - 한 게임 최고기록": "rank_best_lastshot_in_game",
  "임무 기여 처치 - 한 게임 최고기록": "rank_best_mission_kill_in_game",
  "임무 기여 시간 - 한 게임 최고기록": "rank_best_mission_time_in_game",
  "단독 처치 - 한 게임 최고기록": "rank_best_solo_kill_in_game",
  "치명타 - 한 게임 최고기록": "rank_best_critical_in_game",
  "치명타 - 한 목숨 최고기록": "rank_best_critical_in_life",
  "자가 치유 - 한 게임 최고기록": "rank_best_self_heal_in_game",
  "방어형 도움 - 한 게임 최고기록": "rank_best_defence_support",
  "죽음": "rank_death",
  "환경 요소로 죽음": "rank_environment_death",
  "메달 - 동": "rank_bronze_medal",
  "메달 - 은": "rank_silver_medal",
  "메달 - 금": "rank_gold_medal",
  "칭찬 카드": "rank_card",
  "플레이 시간": "rank_playtime",
  "치른 게임": "rank_game_count",
  "승리한 게임": "rank_win",
  "임무 기여 시간": "rank_mission_time",
  "폭주 시간": "rank_flood_time",
  "승률": "rank_win_rate",
  "동시 처치 - 최고기록": "rank_best_onecombo",
  "방어형 도움": "rank_defence_support",
  "재운 적": "rank_enemy_slept",
  "재운 적 - 한 게임 최고기록": "rank_best_enemy_slept_in_game"
 }
}